python ddf_presched.py --ddf_season_frac 0.2 --low_season_fraction 0 --low_season_rate 0
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.15 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.15 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.15 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.20 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.20 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.20 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.30 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.30 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.30 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.40 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.40 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.10 --low_season_fraction 0.40 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.20 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.20 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.20 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.30 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.30 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.30 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.40 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.40 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.15 --low_season_fraction 0.40 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.20 --low_season_fraction 0.30 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.20 --low_season_fraction 0.30 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.20 --low_season_fraction 0.30 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.20 --low_season_fraction 0.40 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.20 --low_season_fraction 0.40 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.20 --low_season_fraction 0.40 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.25 --low_season_fraction 0.30 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.25 --low_season_fraction 0.30 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.25 --low_season_fraction 0.30 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.25 --low_season_fraction 0.40 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.25 --low_season_fraction 0.40 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.25 --low_season_fraction 0.40 --low_season_rate 0.50
python ddf_presched.py --ddf_season_frac 0.30 --low_season_fraction 0.40 --low_season_rate 0.10
python ddf_presched.py --ddf_season_frac 0.30 --low_season_fraction 0.40 --low_season_rate 0.20
python ddf_presched.py --ddf_season_frac 0.30 --low_season_fraction 0.40 --low_season_rate 0.50
