python internal_u.py --u_expt 27 --u_n_scale 0.9
python internal_u.py --u_expt 27 --u_n_scale 1.0
python internal_u.py --u_expt 27 --u_n_scale 1.1
python internal_u.py --u_expt 27 --u_n_scale 1.2
python internal_u.py --u_expt 27 --u_n_scale 1.5
python internal_u.py --u_expt 30 --u_n_scale 0.9
python internal_u.py --u_expt 30 --u_n_scale 1.0
python internal_u.py --u_expt 30 --u_n_scale 1.1
python internal_u.py --u_expt 30 --u_n_scale 1.2
python internal_u.py --u_expt 30 --u_n_scale 1.5
python internal_u.py --u_expt 38 --u_n_scale 0.9
python internal_u.py --u_expt 38 --u_n_scale 1.0
python internal_u.py --u_expt 38 --u_n_scale 1.1
python internal_u.py --u_expt 38 --u_n_scale 1.2
python internal_u.py --u_expt 38 --u_n_scale 1.5
python internal_u.py --u_expt 45 --u_n_scale 0.9
python internal_u.py --u_expt 45 --u_n_scale 1.0
python internal_u.py --u_expt 45 --u_n_scale 1.1
python internal_u.py --u_expt 45 --u_n_scale 1.2
python internal_u.py --u_expt 45 --u_n_scale 1.5
python internal_u.py --u_expt 60 --u_n_scale 0.9
python internal_u.py --u_expt 60 --u_n_scale 1.0
python internal_u.py --u_expt 60 --u_n_scale 1.1
python internal_u.py --u_expt 60 --u_n_scale 1.2
python internal_u.py --u_expt 60 --u_n_scale 1.5
