python too_elab.py --too_days 2 --too_rate 32 --too_filters gz
python too_elab.py --too_days 2 --too_rate 64 --too_filters gz
python too_elab.py --too_days 2 --too_rate 128 --too_filters gz
python too_elab.py --too_days 2 --too_rate 32 --too_filters griz
python too_elab.py --too_days 2 --too_rate 64 --too_filters griz
python too_elab.py --too_days 2 --too_rate 128 --too_filters griz
python too_elab.py --too_days 2 --too_rate 32 --too_filters ugrizy
python too_elab.py --too_days 2 --too_rate 64 --too_filters ugrizy
python too_elab.py --too_days 2 --too_rate 128 --too_filters ugrizy
python too_elab.py --too_days 3 --too_rate 32 --too_filters gz
python too_elab.py --too_days 3 --too_rate 64 --too_filters gz
python too_elab.py --too_days 3 --too_rate 128 --too_filters gz
python too_elab.py --too_days 3 --too_rate 32 --too_filters griz
python too_elab.py --too_days 3 --too_rate 64 --too_filters griz
python too_elab.py --too_days 3 --too_rate 128 --too_filters griz
python too_elab.py --too_days 3 --too_rate 32 --too_filters ugrizy
python too_elab.py --too_days 3 --too_rate 64 --too_filters ugrizy
python too_elab.py --too_days 3 --too_rate 128 --too_filters ugrizy
