python weather.py --cloud_offset_year 0
python weather.py --cloud_offset_year 1
python weather.py --cloud_offset_year 2
python weather.py --cloud_offset_year 4
python weather.py --cloud_offset_year 6
python weather.py --cloud_offset_year 8
python weather.py --cloud_offset_year 10
python weather.py --cloud_offset_year 12
python weather.py --cloud_offset_year 14
python weather.py --cloud_offset_year 16
python weather.py --cloud_offset_year 18
python weather.py --cloud_offset_year 20
python weather.py --cloud_offset_year 30
python weather.py --cloud_offset_year 31
python weather.py --cloud_offset_year 35
python weather.py --cloud_offset_year 36
